### ISSUE TITLE
FileExistsError with pylint 1.8.3

### ISSUE THREAD

**Issue by rossburton** [pradyunsg/installer#106]
If I try and use `installer` to install the pylint 1.8.3 wheel I just built:

```
$ rm -rf foo
$ python3 -minstaller --destdir foo pylint-1.8.3-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ross/Mess/installer/src/installer/__main__.py", line 84, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/home/ross/Mess/installer/src/installer/__main__.py", line 80, in _main
    installer.install(source, destination, {})
  File "/home/ross/Mess/installer/src/installer/_core.py", line 109, in install
    record = destination.write_file(
  File "/home/ross/Mess/installer/src/installer/destinations.py", line 203, in write_file
    return self.write_to_fs(
  File "/home/ross/Mess/installer/src/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: foo/usr/bin/epylint
```
(yes, this is an old release)

This is quite likely a pylint bug, especially as I fixed it by upgrading to the latest release, but `pip` will install the wheel fine so possibly installer should be doing something better to handle wheels like this.

**Comment by FFY00** [comment]
So, the problem here is that the wheel defines both an entrypoint for `epylint` and a script in `.data/scripts`.

**Comment by pradyunsg** [comment]
🤦🏽‍♂️

Of course it does.

**Comment by pradyunsg** [comment]
> `pip` will install the wheel fine so possibly installer should be doing something better to handle wheels like this.

The fact that pip installs such wheels is considered a bug in pip -- https://github.com/pypa/pip/issues/4625. I don't think this package should aim for bug-for-bug compatibility with pip.

**Comment by rossburton** [comment]
Sounds perfectly reasonable to me.  Thought I'd raise it as a difference, obviously bug-for-bug compatibility is exactly the opposite of what should be aimed for here!
