### ISSUE TITLE
KeyError instead of AssertionError

### ISSUE THREAD

**Issue by pawamoy** [pradyunsg/installer#69]
PDM uses installer internally. When installing torch 1.5.1+cpu, I get this error:

```
Install torch 1.5.1+cpu failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/installers.py", line 74, in install_wheel
    _install_wheel(
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/installers.py", line 173, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/usr/local/lib/python3.8/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'caffe2/'
```

I think you simply forgot the default argument of `pop`. I'll open a PR.

See https://github.com/pdm-project/pdm/issues/636

**Comment by pradyunsg** [comment]
Fixed in #72.
